### ISSUE TITLE
Django integration

### ISSUE THREAD

**Issue by mad-marvin** [balena-io-projects/balena-dash#55]
Hey folks, this might not be an issue. Anyway I am working on a project where I want Django and balena Dash on the same device. Is that in any way possible?

**Comment by chrisys** [comment]
@mad-marvin totally, you can always add more containers to the application in order to serve your Django app. You'd do this by modifying the `docker-compose.yml` file to add more services. This isn't really an issue for balenaDash but if you need more assistance doing that, create a post on the forums at https://forums.balena.io and we'll be happy to help.
